<?php

declare(strict_types=1);

return [
    'modules' => [
        'Agents' => 'not-runtime-binary',
        'AiProviders' => 'embedded',
        'Cli' => 'embedded',
        'Config' => 'embedded',
        'Console' => 'embedded',
        'DevServer' => 'embedded',
        'Filesystem' => 'embedded',
        'Http' => 'embedded',
        'HttpClient' => 'embedded',
        'Mark' => 'embedded',
        'Network' => 'embedded',
        'PHPStan' => 'not-runtime-binary',
        'Runtime' => 'embedded',
        'Ssh' => 'not-runtime-binary',
        'Stream' => 'embedded',
        'SurrealDb' => 'not-runtime-binary',
        'Tui' => 'not-runtime-binary',
        'WebSocket' => 'embedded',
        'Worker' => 'embedded',
    ],
    'packages' => [
        ['namespace' => 'Phalanx\\', 'path' => 'phalanx/src/Runtime/src', 'package' => 'phalanx-php/runtime'],
        ['namespace' => 'Phalanx\\Mark\\', 'path' => 'phalanx/src/Mark/src', 'package' => 'phalanx-php/mark'],
        ['namespace' => 'Phalanx\\Console\\', 'path' => 'phalanx/src/Console/src', 'package' => 'phalanx-php/console'],
        ['namespace' => 'Phalanx\\Cli\\', 'path' => 'phalanx/src/Cli/src', 'package' => 'phalanx-php/cli'],
        ['namespace' => 'Phalanx\\Config\\', 'path' => 'phalanx/src/Config/src', 'package' => 'phalanx-php/config'],
        ['namespace' => 'Phalanx\\Stream\\', 'path' => 'phalanx/src/Stream/src', 'package' => 'phalanx-php/stream'],
        ['namespace' => 'Phalanx\\HttpClient\\', 'path' => 'phalanx/src/HttpClient/src', 'package' => 'phalanx-php/http-client'],
        ['namespace' => 'Phalanx\\Filesystem\\', 'path' => 'phalanx/src/Filesystem/src', 'package' => 'phalanx-php/filesystem'],
        ['namespace' => 'Phalanx\\AiProviders\\', 'path' => 'phalanx/src/AiProviders/src', 'package' => 'phalanx-php/ai-providers'],
        ['namespace' => 'Phalanx\\Http\\', 'path' => 'phalanx/src/Http/src', 'package' => 'phalanx-php/http'],
        ['namespace' => 'Phalanx\\Worker\\', 'path' => 'phalanx/src/Worker/src', 'package' => 'phalanx-php/worker'],
        ['namespace' => 'Phalanx\\DevServer\\', 'path' => 'phalanx/src/DevServer/src', 'package' => 'phalanx-php/dev-server'],
        ['namespace' => 'Phalanx\\WebSocket\\', 'path' => 'phalanx/src/WebSocket/src', 'package' => 'phalanx-php/websocket'],
        ['namespace' => 'Phalanx\\Network\\', 'path' => 'phalanx/src/Network/src', 'package' => 'phalanx-php/network'],
        ['namespace' => 'Phalanx\\Bia\\', 'path' => 'libs/bia-runtime/src', 'package' => 'phalanx-php/bia-runtime'],
        ['namespace' => 'GuzzleHttp\\Psr7\\', 'path' => 'phalanx/vendor/guzzlehttp/psr7/src', 'package' => 'guzzlehttp/psr7'],
        ['namespace' => 'Psr\\Http\\Client\\', 'path' => 'phalanx/vendor/psr/http-client/src', 'package' => 'psr/http-client'],
        ['namespace' => 'Psr\\Http\\Message\\', 'path' => 'phalanx/vendor/psr/http-factory/src', 'package' => 'psr/http-factory'],
        ['namespace' => 'Psr\\Http\\Message\\', 'path' => 'phalanx/vendor/psr/http-message/src', 'package' => 'psr/http-message'],
        ['namespace' => 'Psr\\Container\\', 'path' => 'phalanx/vendor/psr/container/src', 'package' => 'psr/container'],
        ['namespace' => 'Psr\\EventDispatcher\\', 'path' => 'phalanx/vendor/psr/event-dispatcher/src', 'package' => 'psr/event-dispatcher'],
        ['namespace' => 'Psr\\Log\\', 'path' => 'phalanx/vendor/psr/log/src', 'package' => 'psr/log'],
        ['namespace' => 'Psr\\SimpleCache\\', 'path' => 'phalanx/vendor/psr/simple-cache/src', 'package' => 'psr/simple-cache'],
        ['namespace' => 'FastRoute\\', 'path' => 'phalanx/vendor/nikic/fast-route/src', 'package' => 'nikic/fast-route'],
        ['namespace' => 'IPLib\\', 'path' => 'phalanx/vendor/mlocati/ip-lib/src', 'package' => 'mlocati/ip-lib'],
        ['namespace' => 'Symfony\\Contracts\\EventDispatcher\\', 'path' => 'phalanx/vendor/symfony/event-dispatcher-contracts', 'package' => 'symfony/event-dispatcher-contracts'],
        ['namespace' => 'Symfony\\Contracts\\Service\\', 'path' => 'phalanx/vendor/symfony/service-contracts', 'package' => 'symfony/service-contracts'],
        ['namespace' => 'Symfony\\Contracts\\Translation\\', 'path' => 'phalanx/vendor/symfony/translation-contracts', 'package' => 'symfony/translation-contracts'],
        ['namespace' => 'Symfony\\Component\\Console\\', 'path' => 'phalanx/vendor/symfony/console', 'package' => 'symfony/console'],
        ['namespace' => 'Symfony\\Component\\EventDispatcher\\', 'path' => 'phalanx/vendor/symfony/event-dispatcher', 'package' => 'symfony/event-dispatcher'],
        ['namespace' => 'Symfony\\Component\\Filesystem\\', 'path' => 'phalanx/vendor/symfony/filesystem', 'package' => 'symfony/filesystem'],
        ['namespace' => 'Symfony\\Component\\Process\\', 'path' => 'phalanx/vendor/symfony/process', 'package' => 'symfony/process'],
        ['namespace' => 'Symfony\\Component\\Runtime\\', 'path' => 'phalanx/vendor/symfony/runtime', 'package' => 'symfony/runtime'],
        ['namespace' => 'Symfony\\Runtime\\Symfony\\Component\\', 'path' => 'phalanx/vendor/symfony/runtime/Internal', 'package' => 'symfony/runtime'],
        ['namespace' => 'Symfony\\Component\\String\\', 'path' => 'phalanx/vendor/symfony/string', 'package' => 'symfony/string'],
        ['namespace' => 'Symfony\\Component\\Uid\\', 'path' => 'phalanx/vendor/symfony/uid', 'package' => 'symfony/uid'],
        ['namespace' => 'Symfony\\Component\\VarDumper\\', 'path' => 'phalanx/vendor/symfony/var-dumper', 'package' => 'symfony/var-dumper'],
        ['namespace' => 'Symfony\\Polyfill\\Ctype\\', 'path' => 'phalanx/vendor/symfony/polyfill-ctype', 'package' => 'symfony/polyfill-ctype'],
        ['namespace' => 'Symfony\\Polyfill\\Intl\\Grapheme\\', 'path' => 'phalanx/vendor/symfony/polyfill-intl-grapheme', 'package' => 'symfony/polyfill-intl-grapheme'],
        ['namespace' => 'Symfony\\Polyfill\\Intl\\Idn\\', 'path' => 'phalanx/vendor/symfony/polyfill-intl-idn', 'package' => 'symfony/polyfill-intl-idn'],
        ['namespace' => 'Symfony\\Polyfill\\Intl\\Normalizer\\', 'path' => 'phalanx/vendor/symfony/polyfill-intl-normalizer', 'package' => 'symfony/polyfill-intl-normalizer'],
        ['namespace' => 'Symfony\\Polyfill\\Mbstring\\', 'path' => 'phalanx/vendor/symfony/polyfill-mbstring', 'package' => 'symfony/polyfill-mbstring'],
        ['namespace' => 'Symfony\\Polyfill\\Php80\\', 'path' => 'phalanx/vendor/symfony/polyfill-php80', 'package' => 'symfony/polyfill-php80'],
        ['namespace' => 'Symfony\\Polyfill\\Php81\\', 'path' => 'phalanx/vendor/symfony/polyfill-php81', 'package' => 'symfony/polyfill-php81'],
        ['namespace' => 'Symfony\\Polyfill\\Php84\\', 'path' => 'phalanx/vendor/symfony/polyfill-php84', 'package' => 'symfony/polyfill-php84'],
        ['namespace' => 'Symfony\\Polyfill\\Php85\\', 'path' => 'phalanx/vendor/symfony/polyfill-php85', 'package' => 'symfony/polyfill-php85'],
        ['namespace' => 'Symfony\\Polyfill\\Php86\\', 'path' => 'phalanx/vendor/symfony/polyfill-php86', 'package' => 'symfony/polyfill-php86'],
        ['namespace' => 'Symfony\\Polyfill\\Uuid\\', 'path' => 'phalanx/vendor/symfony/polyfill-uuid', 'package' => 'symfony/polyfill-uuid'],
    ],
    'eager_files' => [
        'functions.php' => 'libs/bia-runtime/src/functions.php',
        'vendor/ralouphie/getallheaders/src/getallheaders.php' => 'phalanx/vendor/ralouphie/getallheaders/src/getallheaders.php',
        'vendor/nikic/fast-route/src/functions.php' => 'phalanx/vendor/nikic/fast-route/src/functions.php',
        'vendor/symfony/deprecation-contracts/function.php' => 'phalanx/vendor/symfony/deprecation-contracts/function.php',
        'vendor/symfony/polyfill-ctype/bootstrap.php' => 'phalanx/vendor/symfony/polyfill-ctype/bootstrap.php',
        'vendor/symfony/polyfill-ctype/bootstrap80.php' => 'phalanx/vendor/symfony/polyfill-ctype/bootstrap80.php',
        'vendor/symfony/polyfill-intl-grapheme/bootstrap.php' => 'phalanx/vendor/symfony/polyfill-intl-grapheme/bootstrap.php',
        'vendor/symfony/polyfill-intl-grapheme/bootstrap80.php' => 'phalanx/vendor/symfony/polyfill-intl-grapheme/bootstrap80.php',
        'vendor/symfony/polyfill-intl-idn/bootstrap.php' => 'phalanx/vendor/symfony/polyfill-intl-idn/bootstrap.php',
        'vendor/symfony/polyfill-intl-idn/bootstrap80.php' => 'phalanx/vendor/symfony/polyfill-intl-idn/bootstrap80.php',
        'vendor/symfony/polyfill-intl-normalizer/bootstrap.php' => 'phalanx/vendor/symfony/polyfill-intl-normalizer/bootstrap.php',
        'vendor/symfony/polyfill-intl-normalizer/bootstrap80.php' => 'phalanx/vendor/symfony/polyfill-intl-normalizer/bootstrap80.php',
        'vendor/symfony/polyfill-mbstring/bootstrap.php' => 'phalanx/vendor/symfony/polyfill-mbstring/bootstrap.php',
        'vendor/symfony/polyfill-mbstring/bootstrap80.php' => 'phalanx/vendor/symfony/polyfill-mbstring/bootstrap80.php',
        'vendor/symfony/polyfill-php80/bootstrap.php' => 'phalanx/vendor/symfony/polyfill-php80/bootstrap.php',
        'vendor/symfony/polyfill-php81/bootstrap.php' => 'phalanx/vendor/symfony/polyfill-php81/bootstrap.php',
        'vendor/symfony/polyfill-php84/bootstrap.php' => 'phalanx/vendor/symfony/polyfill-php84/bootstrap.php',
        'vendor/symfony/polyfill-php84/bootstrap82.php' => 'phalanx/vendor/symfony/polyfill-php84/bootstrap82.php',
        'vendor/symfony/polyfill-php85/bootstrap.php' => 'phalanx/vendor/symfony/polyfill-php85/bootstrap.php',
        'vendor/symfony/polyfill-php85/bootstrap80.php' => 'phalanx/vendor/symfony/polyfill-php85/bootstrap80.php',
        'vendor/symfony/polyfill-php86/bootstrap.php' => 'phalanx/vendor/symfony/polyfill-php86/bootstrap.php',
        'vendor/symfony/polyfill-php86/bootstrap80.php' => 'phalanx/vendor/symfony/polyfill-php86/bootstrap80.php',
        'vendor/symfony/polyfill-uuid/bootstrap.php' => 'phalanx/vendor/symfony/polyfill-uuid/bootstrap.php',
        'vendor/symfony/polyfill-uuid/bootstrap80.php' => 'phalanx/vendor/symfony/polyfill-uuid/bootstrap80.php',
        'vendor/symfony/string/Resources/functions.php' => 'phalanx/vendor/symfony/string/Resources/functions.php',
        'vendor/symfony/var-dumper/Resources/functions/dump.php' => 'phalanx/vendor/symfony/var-dumper/Resources/functions/dump.php',
    ],
    'smoke_symbols' => [
        'classes' => [
            'Phalanx\\Application',
            'Phalanx\\Bia\\Runtime\\ScriptContext',
            'Phalanx\\AiProviders\\Provider\\Registry',
            'Phalanx\\Cli\\Scaffold\\ProjectGenerator',
            'Phalanx\\Config\\ConfigHydrator',
            'Phalanx\\Console\\Console',
            'Phalanx\\DevServer\\ManagedProcess',
            'Phalanx\\Filesystem\\Filesystem',
            'Phalanx\\Http\\FastRouteCompiler',
            'Phalanx\\HttpClient\\Client',
            'Phalanx\\Mark\\Mark',
            'Phalanx\\Network\\Subnet',
            'Phalanx\\Stream\\Stream',
            'Phalanx\\WebSocket\\RouteConfig',
            'Phalanx\\Worker\\Worker',
            'GuzzleHttp\\Psr7\\ServerRequest',
            'IPLib\\Factory',
            'Psr\\Http\\Message\\ResponseInterface',
            'Symfony\\Component\\Console\\Application',
            'Symfony\\Component\\Runtime\\GenericRuntime',
        ],
        'functions' => [
            'FastRoute\\simpleDispatcher',
            'dump',
        ],
    ],
];
