[workspace]
members = [".", "xtask"]

[package]
name = "bia"
version = "0.1.0"
edition = "2024"
rust-version = "1.95.0"
description = "Phalanx Scripting Environment"

[dependencies]
ripht-php-sapi = { git = "https://github.com/jhavenz/ripht-php-sapi", rev = "030265a6130edca9443dfd4964e7d96d9c5a9ed9" }
tempfile = "3.27.0"
clap = { version = "4", features = ["derive"] }
signal-hook = "0.3"
tar = "0.4"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.9"
libc = "0.2"
bumpalo = "3.19.0"
mago-database = "1.29.0"
mago-span = "1.29.0"
mago-syntax = "1.29.0"
mago-syntax-core = "1.29.0"

[profile.release]
strip = true
lto = true
codegen-units = 1
