[workspace]
members = [".", "xtask"]

[package]
name = "dory"
version = "0.1.0"
edition = "2021"
description = "Phalanx Scripting Environment"

[dependencies]
ripht-php-sapi = { git = "https://github.com/jhavenz/ripht-php-sapi.git", rev = "1e42f9947db58d6aaa6c54af911e738094868176" }
tempfile = "3.27.0"
clap = { version = "4", features = ["derive"] }
signal-hook = "0.3"
tar = "0.4"
serde_json = "1.0"
libc = "0.2"

[profile.release]
strip = true
lto = true
codegen-units = 1
