#!/usr/bin/env bash
set -euo pipefail

# Dory Static Runtime Builder
# Orchestrates StaticPHP v3 to compile libphp.a from craft.yml.

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$DIR")"

DEFAULT_STATIC_PHP_PREFIX="$ROOT_DIR/.ripht/php"
DORY_STATIC_PHP_PREFIX="${DORY_STATIC_PHP_PREFIX:-$DEFAULT_STATIC_PHP_PREFIX}"
SPC_WORK_DIR="${SPC_WORK_DIR:-$ROOT_DIR/.spc-work}"
SPC_BIN="${DORY_SPC_BIN:-}"
SPC_VERSION="${SPC_VERSION:-nightly}"
SPC_BASE_URL="${SPC_BASE_URL:-https://dl.static-php.dev/v3/spc-bin/$SPC_VERSION}"

echo "=== Dory Static Runtime Builder ==="
echo "Reading configuration from $ROOT_DIR/craft.yml"

case "$(uname -s)" in
    Darwin) SPC_OS="macos" ;;
    Linux) SPC_OS="linux" ;;
    *) echo "Unsupported OS for SPC v3 binary: $(uname -s)" >&2; exit 1 ;;
esac

case "$(uname -m)" in
    arm64|aarch64) SPC_ARCH="aarch64" ;;
    x86_64|amd64) SPC_ARCH="x86_64" ;;
    *) echo "Unsupported architecture for SPC v3 binary: $(uname -m)" >&2; exit 1 ;;
esac

case "$DORY_STATIC_PHP_PREFIX" in
    ""|"/"|"/usr"|"/usr/"|"/usr/local"|"/usr/local/"|"/opt"|"/opt/")
        echo "Refusing unsafe DORY_STATIC_PHP_PREFIX: $DORY_STATIC_PHP_PREFIX" >&2
        exit 1
        ;;
esac

MARKER_FILE="$DORY_STATIC_PHP_PREFIX/.dory-static-runtime"

if [ "$DORY_STATIC_PHP_PREFIX" != "$DEFAULT_STATIC_PHP_PREFIX" ] && [ ! -f "$MARKER_FILE" ] && [ "${DORY_ALLOW_UNMARKED_PREFIX:-}" != "1" ]; then
    echo "Refusing to overwrite unmarked DORY_STATIC_PHP_PREFIX: $DORY_STATIC_PHP_PREFIX" >&2
    echo "Set DORY_ALLOW_UNMARKED_PREFIX=1 for the first install into a custom prefix." >&2
    exit 1
fi

if [ -z "$SPC_BIN" ]; then
    mkdir -p "$ROOT_DIR/.spc"
    SPC_BIN="$ROOT_DIR/.spc/spc-$SPC_OS-$SPC_ARCH"

    if [ ! -x "$SPC_BIN" ]; then
        echo "Downloading StaticPHP v3 SPC: $SPC_OS-$SPC_ARCH"
        curl -#fSL "$SPC_BASE_URL/spc-$SPC_OS-$SPC_ARCH" -o "$SPC_BIN"
        chmod +x "$SPC_BIN"
    fi
fi

mkdir -p "$SPC_WORK_DIR"
cd "$SPC_WORK_DIR"

echo "=== Phase 1: StaticPHP v3 toolchain ==="
"$SPC_BIN" --version
"$SPC_BIN" install-pkg --no-interaction --dl-parallel=8 --dl-retry=5 --dl-prefer-binary=true -- pkg-config

echo "=== Phase 2: StaticPHP v3 craft ==="
"$SPC_BIN" craft --no-interaction "$ROOT_DIR/craft.yml"

echo "=== Phase 3: Install static PHP runtime ==="
rm -rf "$DORY_STATIC_PHP_PREFIX/lib" "$DORY_STATIC_PHP_PREFIX/bin" "$DORY_STATIC_PHP_PREFIX/include/php" "$DORY_STATIC_PHP_PREFIX/etc/dory/php"
mkdir -p "$DORY_STATIC_PHP_PREFIX/lib" "$DORY_STATIC_PHP_PREFIX/bin" "$DORY_STATIC_PHP_PREFIX/include" "$DORY_STATIC_PHP_PREFIX/etc/dory/php/conf.d"
touch "$MARKER_FILE"

cp "buildroot/lib/libphp.a" "$DORY_STATIC_PHP_PREFIX/lib/libphp.a"

cp -r "buildroot/include/php" "$DORY_STATIC_PHP_PREFIX/include/php"

for src in buildroot/lib/*.a; do
    if [ -f "$src" ]; then
        cp "$src" "$DORY_STATIC_PHP_PREFIX/lib/"
    fi
done

if [ "$SPC_OS" = "linux" ]; then
    ZIG_LIB_DIR="$SPC_WORK_DIR/pkgroot/$SPC_ARCH-linux/zig/lib"
    for lib in "libc++.a" "libc++abi.a" "libunwind.a"; do
        if [ -f "$ZIG_LIB_DIR/$lib" ]; then
            cp "$ZIG_LIB_DIR/$lib" "$DORY_STATIC_PHP_PREFIX/lib/"
        fi
    done
fi

if [ -d "buildroot/lib/pkgconfig" ]; then
    cp -r "buildroot/lib/pkgconfig" "$DORY_STATIC_PHP_PREFIX/lib/pkgconfig"
fi

BUILDROOT_DIR="$(pwd)/buildroot"

perl -0pe 'BEGIN { $from = shift @ARGV; $to = shift @ARGV } s/\Q$from\E/$to/g' "$BUILDROOT_DIR" "$DORY_STATIC_PHP_PREFIX" "buildroot/bin/php-config" > "$DORY_STATIC_PHP_PREFIX/bin/php-config"
chmod +x "$DORY_STATIC_PHP_PREFIX/bin/php-config"

{
    echo "# Generated by scripts/build-static-engine.sh; consumed by build.rs."
    echo "ldflags=$("$DORY_STATIC_PHP_PREFIX/bin/php-config" --ldflags)"
    PHP_LIBS="$("$DORY_STATIC_PHP_PREFIX/bin/php-config" --libs)"
    if [ "$SPC_OS" = "linux" ]; then
        PHP_LIBS="${PHP_LIBS//-lstdc++/-lc++ -lc++abi}"
    fi
    echo "libs=-lphp $PHP_LIBS"
} > "$DORY_STATIC_PHP_PREFIX/lib/dory-link-flags.txt"

echo "=== Success ==="
echo "libphp.a installed to: $DORY_STATIC_PHP_PREFIX/lib/libphp.a"
ls -lh "$DORY_STATIC_PHP_PREFIX/lib/libphp.a"
