use std::path::Path;

pub const TARGET_DIR: &str = "../bia-runtime/src/Runtime/Host";

pub struct GeneratedFile {
    pub path: &'static str,
    pub contents: &'static str,
}

pub fn generated_files() -> [GeneratedFile; 8] {
    [
        GeneratedFile {
            path: "AppEnv.php",
            contents: APP_ENV,
        },
        GeneratedFile {
            path: "BiaFacts.php",
            contents: BIA_FACTS,
        },
        GeneratedFile {
            path: "EnvFacts.php",
            contents: ENV_FACTS,
        },
        GeneratedFile {
            path: "HostFacts.php",
            contents: HOST_FACTS,
        },
        GeneratedFile {
            path: "PathFacts.php",
            contents: PATH_FACTS,
        },
        GeneratedFile {
            path: "PhpFacts.php",
            contents: PHP_FACTS,
        },
        GeneratedFile {
            path: "ServeFacts.php",
            contents: SERVE_FACTS,
        },
        GeneratedFile {
            path: "SwooleFacts.php",
            contents: SWOOLE_FACTS,
        },
    ]
}

pub fn write_to(root: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let target = root.join(TARGET_DIR);

    std::fs::create_dir_all(&target)?;

    for file in generated_files() {
        std::fs::write(target.join(file.path), file.contents)?;
    }

    Ok(())
}

pub fn check_fresh(root: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let target = root.join(TARGET_DIR);
    let mut stale = Vec::new();

    for file in generated_files() {
        let path = target.join(file.path);
        match std::fs::read_to_string(&path) {
            Ok(existing) if existing == file.contents => {}
            Ok(_) => stale.push(file.path.to_string()),
            Err(_) => stale.push(file.path.to_string()),
        }
    }

    if stale.is_empty() {
        return Ok(());
    }

    Err(format!(
        "host facts generated files are stale or missing: {} (run cargo xtask gen-host-facts)",
        stale.join(", ")
    )
    .into())
}

macro_rules! header {
    () => {
        "<?php\n\ndeclare(strict_types=1);\n\n// GENERATED by cargo xtask gen-host-facts. Do not edit by hand.\n\nnamespace Phalanx\\Bia\\Runtime\\Host;\n\n"
    };
}

macro_rules! list_helper {
    () => {
        "    /** @return list<string> */\n    private static function listOfString(mixed $value, string $path): array\n    {\n        if (!is_array($value) || array_is_list($value) === false) {\n            throw new InvalidArgumentException(\"{$path} must be list<string>.\");\n        }\n\n        foreach ($value as $item) {\n            if (!is_string($item)) {\n                throw new InvalidArgumentException(\"{$path} must be list<string>.\");\n            }\n        }\n\n        return $value;\n    }\n\n"
    };
}

macro_rules! shape_helper {
    () => {
        "    /** @param array<string, mixed> $data @param list<string> $keys */\n    private static function assertShape(array $data, array $keys, string $type): void\n    {\n        $actual = array_keys($data);\n        $missing = array_values(array_diff($keys, $actual));\n        $unknown = array_values(array_diff($actual, $keys));\n\n        if ($missing !== []) {\n            throw new InvalidArgumentException($type . ' missing keys: ' . implode(', ', $missing));\n        }\n\n        if ($unknown !== []) {\n            throw new InvalidArgumentException($type . ' unknown keys: ' . implode(', ', $unknown));\n        }\n    }\n\n"
    };
}

const APP_ENV: &str = concat!(
    header!(),
    "enum AppEnv: string\n",
    "{\n",
    "    case Dev = 'dev';\n",
    "    case Test = 'test';\n",
    "    case Prod = 'prod';\n",
    "}\n",
);

const BIA_FACTS: &str = concat!(
    header!(),
    "use InvalidArgumentException;\n\n",
    "final class BiaFacts\n",
    "{\n",
    "    public function __construct(\n",
    "        private(set) ?int $timeoutMs,\n",
    "        private(set) ?int $concurrency,\n",
    "        private(set) bool $verbose,\n",
    "    ) {\n",
    "    }\n\n",
    "    /** @param array<string, mixed> $data */\n",
    "    public static function hydrate(array $data): self\n",
    "    {\n",
    "        self::assertShape($data, ['timeout_ms', 'concurrency', 'verbose'], 'BiaFacts');\n",
    "        $timeout = $data['timeout_ms'];\n",
    "        $concurrency = $data['concurrency'];\n",
    "        if ($timeout !== null && !is_int($timeout)) { throw new InvalidArgumentException('BiaFacts.timeout_ms must be int|null.'); }\n",
    "        if ($concurrency !== null && !is_int($concurrency)) { throw new InvalidArgumentException('BiaFacts.concurrency must be int|null.'); }\n",
    "        if (!is_bool($data['verbose'])) { throw new InvalidArgumentException('BiaFacts.verbose must be bool.'); }\n",
    "        return new self($timeout, $concurrency, $data['verbose']);\n",
    "    }\n\n",
    "    /** @return array{timeout_ms: ?int, concurrency: ?int, verbose: bool} */\n",
    "    public function toArray(): array\n",
    "    {\n",
    "        return ['timeout_ms' => $this->timeoutMs, 'concurrency' => $this->concurrency, 'verbose' => $this->verbose];\n",
    "    }\n\n",
    shape_helper!(),
    "}\n",
);

const ENV_FACTS: &str = concat!(
    header!(),
    "use InvalidArgumentException;\n\n",
    "final class EnvFacts\n",
    "{\n",
    "    /** @param list<string> $sources @param array<string, array{value: string, source: string, line: ?int}> $values @param list<array{severity: string, code: string, message: string, key: ?string, source: ?string, line: ?int}> $issues */\n",
    "    public function __construct(\n",
    "        private(set) array $sources,\n",
    "        private(set) array $values,\n",
    "        private(set) array $issues,\n",
    "    ) {\n",
    "    }\n\n",
    "    /** @param array<string, mixed> $data */\n",
    "    public static function hydrate(array $data): self\n",
    "    {\n",
    "        self::assertShape($data, ['sources', 'values', 'issues'], 'EnvFacts');\n",
    "        $sources = self::listOfString($data['sources'], 'EnvFacts.sources');\n",
    "        if (!is_array($data['values'])) { throw new InvalidArgumentException('EnvFacts.values must be object.'); }\n",
    "        $values = [];\n",
    "        foreach ($data['values'] as $key => $value) {\n",
    "            if (!is_string($key) || !is_array($value)) { throw new InvalidArgumentException('EnvFacts.values must be array<string, object>.'); }\n",
    "            self::assertShape($value, ['value', 'source', 'line'], 'EnvFacts.values.' . $key);\n",
    "            if (!is_string($value['value']) || !is_string($value['source']) || ($value['line'] !== null && !is_int($value['line']))) { throw new InvalidArgumentException('EnvFacts.values.' . $key . ' has invalid fields.'); }\n",
    "            $values[$key] = ['value' => $value['value'], 'source' => $value['source'], 'line' => $value['line']];\n",
    "        }\n",
    "        if (!is_array($data['issues']) || array_is_list($data['issues']) === false) { throw new InvalidArgumentException('EnvFacts.issues must be list<object>.'); }\n",
    "        $issues = [];\n",
    "        foreach ($data['issues'] as $issue) {\n",
    "            if (!is_array($issue)) { throw new InvalidArgumentException('EnvFacts.issues must be list<object>.'); }\n",
    "            self::assertShape($issue, ['severity', 'code', 'message', 'key', 'source', 'line'], 'EnvFacts.issue');\n",
    "            if (!is_string($issue['severity']) || !in_array($issue['severity'], ['warn', 'error'], true)) { throw new InvalidArgumentException('EnvFacts.issue.severity must be warn|error.'); }\n",
    "            if (!is_string($issue['code']) || !is_string($issue['message'])) { throw new InvalidArgumentException('EnvFacts.issue code/message must be strings.'); }\n",
    "            if ($issue['key'] !== null && !is_string($issue['key'])) { throw new InvalidArgumentException('EnvFacts.issue.key must be string|null.'); }\n",
    "            if ($issue['source'] !== null && !is_string($issue['source'])) { throw new InvalidArgumentException('EnvFacts.issue.source must be string|null.'); }\n",
    "            if ($issue['line'] !== null && !is_int($issue['line'])) { throw new InvalidArgumentException('EnvFacts.issue.line must be int|null.'); }\n",
    "            $issues[] = $issue;\n",
    "        }\n",
    "        return new self($sources, $values, $issues);\n",
    "    }\n\n",
    "    /** @return array{sources: list<string>, values: object, issues: list<array{severity: string, code: string, message: string, key: ?string, source: ?string, line: ?int}>} */\n",
    "    public function toArray(): array\n",
    "    {\n",
    "        return ['sources' => $this->sources, 'values' => $this->values === [] ? (object) [] : $this->values, 'issues' => $this->issues];\n",
    "    }\n\n",
    list_helper!(),
    shape_helper!(),
    "}\n",
);

const HOST_FACTS: &str = concat!(
    header!(),
    "use InvalidArgumentException;\n",
    "use RuntimeException;\n\n",
    "final class HostFacts\n",
    "{\n",
    "    public const int CONTRACT = 1;\n\n",
    "    /** @param list<string> $argv */\n",
    "    public function __construct(\n",
    "        private(set) int $contract,\n",
    "        private(set) bool $embedded,\n",
    "        private(set) array $argv,\n",
    "        private(set) AppEnv $appEnv,\n",
    "        private(set) EnvFacts $env,\n",
    "        private(set) PhpFacts $php,\n",
    "        private(set) SwooleFacts $swoole,\n",
    "        private(set) ?ServeFacts $serve,\n",
    "        private(set) BiaFacts $bia,\n",
    "        private(set) PathFacts $paths,\n",
    "    ) {\n",
    "    }\n\n",
    "    /** @param array<string, mixed> $data */\n",
    "    public static function hydrate(array $data): self\n",
    "    {\n",
    "        self::assertShape($data, ['contract', 'embedded', 'argv', 'app_env', 'env', 'php', 'swoole', 'serve', 'bia', 'paths'], 'HostFacts');\n",
    "        if (!is_int($data['contract'])) { throw new InvalidArgumentException('HostFacts.contract must be int.'); }\n",
    "        if ($data['contract'] !== self::CONTRACT) {\n",
    "            throw new RuntimeException(\"handoff contract mismatch: host speaks v{$data['contract']}, runtime expects v\" . self::CONTRACT . \"\\n-> upgrade bia or pin phalanx-php/phalanx\");\n",
    "        }\n",
    "        if (!is_bool($data['embedded'])) { throw new InvalidArgumentException('HostFacts.embedded must be bool.'); }\n",
    "        $argv = self::listOfString($data['argv'], 'HostFacts.argv');\n",
    "        $appEnv = is_string($data['app_env']) ? AppEnv::from($data['app_env']) : throw new InvalidArgumentException('HostFacts.app_env must be string.');\n",
    "        $env = is_array($data['env']) ? EnvFacts::hydrate($data['env']) : throw new InvalidArgumentException('HostFacts.env must be object.');\n",
    "        $php = is_array($data['php']) ? PhpFacts::hydrate($data['php']) : throw new InvalidArgumentException('HostFacts.php must be object.');\n",
    "        $swoole = is_array($data['swoole']) ? SwooleFacts::hydrate($data['swoole']) : throw new InvalidArgumentException('HostFacts.swoole must be object.');\n",
    "        $serve = $data['serve'] === null ? null : (is_array($data['serve']) ? ServeFacts::hydrate($data['serve']) : throw new InvalidArgumentException('HostFacts.serve must be object|null.'));\n",
    "        $bia = is_array($data['bia']) ? BiaFacts::hydrate($data['bia']) : throw new InvalidArgumentException('HostFacts.bia must be object.');\n",
    "        $paths = is_array($data['paths']) ? PathFacts::hydrate($data['paths']) : throw new InvalidArgumentException('HostFacts.paths must be object.');\n",
    "        return new self($data['contract'], $data['embedded'], $argv, $appEnv, $env, $php, $swoole, $serve, $bia, $paths);\n",
    "    }\n\n",
    "    /** @return array<string, mixed> */\n",
    "    public function toArray(): array\n",
    "    {\n",
    "        return [\n",
    "            'contract' => $this->contract,\n",
    "            'embedded' => $this->embedded,\n",
    "            'argv' => $this->argv,\n",
    "            'app_env' => $this->appEnv->value,\n",
    "            'env' => $this->env->toArray(),\n",
    "            'php' => $this->php->toArray(),\n",
    "            'swoole' => $this->swoole->toArray(),\n",
    "            'serve' => $this->serve?->toArray(),\n",
    "            'bia' => $this->bia->toArray(),\n",
    "            'paths' => $this->paths->toArray(),\n",
    "        ];\n",
    "    }\n\n",
    list_helper!(),
    shape_helper!(),
    "}\n",
);

const PATH_FACTS: &str = concat!(
    header!(),
    "use InvalidArgumentException;\n\n",
    "final class PathFacts\n",
    "{\n",
    "    /** @param list<string> $watch */\n",
    "    public function __construct(\n",
    "        private(set) string $runtimeDir,\n",
    "        private(set) string $cwd,\n",
    "        private(set) array $watch,\n",
    "    ) {\n",
    "    }\n\n",
    "    /** @param array<string, mixed> $data */\n",
    "    public static function hydrate(array $data): self\n",
    "    {\n",
    "        self::assertShape($data, ['runtime_dir', 'cwd', 'watch'], 'PathFacts');\n",
    "        if (!is_string($data['runtime_dir'])) { throw new InvalidArgumentException('PathFacts.runtime_dir must be string.'); }\n",
    "        if (!is_string($data['cwd'])) { throw new InvalidArgumentException('PathFacts.cwd must be string.'); }\n",
    "        return new self($data['runtime_dir'], $data['cwd'], self::listOfString($data['watch'], 'PathFacts.watch'));\n",
    "    }\n\n",
    "    /** @return array{runtime_dir: string, cwd: string, watch: list<string>} */\n",
    "    public function toArray(): array\n",
    "    {\n",
    "        return ['runtime_dir' => $this->runtimeDir, 'cwd' => $this->cwd, 'watch' => $this->watch];\n",
    "    }\n\n",
    list_helper!(),
    shape_helper!(),
    "}\n",
);

const PHP_FACTS: &str = concat!(
    header!(),
    "use InvalidArgumentException;\n\n",
    "final class PhpFacts\n",
    "{\n",
    "    /** @param array<string, string> $ini */\n",
    "    public function __construct(\n",
    "        private(set) string $memoryLimit,\n",
    "        private(set) array $ini,\n",
    "    ) {\n",
    "    }\n\n",
    "    /** @param array<string, mixed> $data */\n",
    "    public static function hydrate(array $data): self\n",
    "    {\n",
    "        self::assertShape($data, ['memory_limit', 'ini'], 'PhpFacts');\n",
    "        if (!is_string($data['memory_limit'])) { throw new InvalidArgumentException('PhpFacts.memory_limit must be string.'); }\n",
    "        if (!is_array($data['ini'])) { throw new InvalidArgumentException('PhpFacts.ini must be object.'); }\n",
    "        $ini = [];\n",
    "        foreach ($data['ini'] as $key => $value) {\n",
    "            if (!is_string($key) || !is_string($value)) { throw new InvalidArgumentException('PhpFacts.ini must be array<string, string>.'); }\n",
    "            $ini[$key] = $value;\n",
    "        }\n",
    "        return new self($data['memory_limit'], $ini);\n",
    "    }\n\n",
    "    /** @return array{memory_limit: string, ini: array<string, string>} */\n",
    "    public function toArray(): array\n",
    "    {\n",
    "        return ['memory_limit' => $this->memoryLimit, 'ini' => $this->ini];\n",
    "    }\n\n",
    shape_helper!(),
    "}\n",
);

const SERVE_FACTS: &str = concat!(
    header!(),
    "use InvalidArgumentException;\n\n",
    "final class ServeFacts\n",
    "{\n",
    "    public function __construct(\n",
    "        private(set) string $listen,\n",
    "    ) {\n",
    "    }\n\n",
    "    /** @param array<string, mixed> $data */\n",
    "    public static function hydrate(array $data): self\n",
    "    {\n",
    "        self::assertShape($data, ['listen'], 'ServeFacts');\n",
    "        if (!is_string($data['listen'])) { throw new InvalidArgumentException('ServeFacts.listen must be string.'); }\n",
    "        return new self($data['listen']);\n",
    "    }\n\n",
    "    /** @return array{listen: string} */\n",
    "    public function toArray(): array\n",
    "    {\n",
    "        return ['listen' => $this->listen];\n",
    "    }\n\n",
    shape_helper!(),
    "}\n",
);

const SWOOLE_FACTS: &str = concat!(
    header!(),
    "use InvalidArgumentException;\n\n",
    "final class SwooleFacts\n",
    "{\n",
    "    /** @param list<string> $hooks */\n",
    "    public function __construct(\n",
    "        private(set) int $eventWorkers,\n",
    "        private(set) int $taskWorkers,\n",
    "        private(set) array $hooks,\n",
    "    ) {\n",
    "    }\n\n",
    "    /** @param array<string, mixed> $data */\n",
    "    public static function hydrate(array $data): self\n",
    "    {\n",
    "        self::assertShape($data, ['event_workers', 'task_workers', 'hooks'], 'SwooleFacts');\n",
    "        if (!is_int($data['event_workers'])) { throw new InvalidArgumentException('SwooleFacts.event_workers must be int.'); }\n",
    "        if (!is_int($data['task_workers'])) { throw new InvalidArgumentException('SwooleFacts.task_workers must be int.'); }\n",
    "        return new self($data['event_workers'], $data['task_workers'], self::listOfString($data['hooks'], 'SwooleFacts.hooks'));\n",
    "    }\n\n",
    "    /** @return array{event_workers: int, task_workers: int, hooks: list<string>} */\n",
    "    public function toArray(): array\n",
    "    {\n",
    "        return ['event_workers' => $this->eventWorkers, 'task_workers' => $this->taskWorkers, 'hooks' => $this->hooks];\n",
    "    }\n\n",
    list_helper!(),
    shape_helper!(),
    "}\n",
);
