//! HostFacts: the serde/JSON facts channel (HB-02). One versioned struct,
//! serialized once per boot and delivered to PHP through the
//! phalanx_host_facts() native call - no env side channels. The PHP value
//! classes are generated by `cargo xtask gen-host-facts`; the round-trip
//! integration test keeps both ends in lockstep.

use std::collections::BTreeMap;
use std::path::Path;
use std::sync::OnceLock;

use serde::Serialize;

use crate::env_map::EnvMap;
use crate::host_config::{HostConfig, SwooleHook, WorkerCount};

/// The handoff version. PHP refuses to boot when its generated class
/// expects a different contract.
pub const CONTRACT: u32 = 1;

static PUBLISHED: OnceLock<String> = OnceLock::new();

/// Serializes the facts once for the lifetime of the process; the native
/// function hands this string to PHP.
pub fn publish(facts: &HostFacts) {
    let json = serde_json::to_string(facts).expect("host facts are plain serializable data");

    PUBLISHED
        .set(json)
        .expect("host facts publish exactly once");
}

pub fn published_json() -> Option<&'static str> {
    PUBLISHED.get().map(String::as_str)
}

#[derive(Debug, Serialize)]
pub struct HostFacts {
    contract: u32,
    embedded: bool,
    argv: Vec<String>,
    app_env: AppEnv,
    env: EnvMap,
    php: PhpFacts,
    swoole: SwooleFacts,
    serve: Option<ServeFacts>,
    bia: BiaFacts,
    paths: PathFacts,
}

impl HostFacts {
    /// The generic runtime reports embedded: false - the flag distinguishes
    /// future baked per-app binaries from day one.
    pub fn gather(config: &HostConfig, input: HostFactInput<'_>) -> Self {
        Self {
            contract: CONTRACT,
            embedded: false,
            argv: input.argv,
            app_env: input.app_env,
            env: input.env,
            php: PhpFacts {
                memory_limit: input.memory_limit.to_string(),
                ini: config
                    .php
                    .ini
                    .iter()
                    .map(|(key, value)| (key.clone(), value.as_ini_value()))
                    .collect(),
            },
            swoole: SwooleFacts {
                event_workers: match config.swoole.event_workers {
                    WorkerCount::Auto => detected_parallelism(),
                    WorkerCount::Fixed(count) => count,
                },
                task_workers: config.swoole.task_workers,
                hooks: config.swoole.hooks.clone(),
            },
            serve: config.serve.as_ref().map(|serve| ServeFacts {
                listen: serve.listen.0.to_string(),
            }),
            bia: BiaFacts {
                timeout_ms: config
                    .bia
                    .timeout
                    .map(|timeout| timeout.0.as_millis() as u64),
                concurrency: config.bia.concurrency,
                verbose: input.verbose,
            },
            paths: PathFacts {
                runtime_dir: input.runtime_dir.to_string_lossy().into_owned(),
                cwd: input.cwd.to_string_lossy().into_owned(),
                watch: config.dev.watch.clone(),
            },
        }
    }
}

pub struct HostFactInput<'a> {
    pub app_env: AppEnv,
    pub env: EnvMap,
    pub argv: Vec<String>,
    pub runtime_dir: &'a Path,
    pub cwd: &'a Path,
    pub memory_limit: &'a str,
    pub verbose: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum AppEnv {
    Dev,
    Test,
    Prod,
}

impl AppEnv {
    /// Unset or empty means dev; anything else must name a real env.
    pub fn detect_from(env: &EnvMap) -> Result<Self, String> {
        match env.get("APP_ENV") {
            None => Ok(Self::Dev),
            Some(value) => Self::named(value),
        }
    }

    fn named(value: &str) -> Result<Self, String> {
        match value {
            "" | "dev" => Ok(Self::Dev),
            "test" => Ok(Self::Test),
            "prod" => Ok(Self::Prod),
            other => Err(format!(
                "APP_ENV \"{other}\" is not an app env (expected dev, test, or prod)"
            )),
        }
    }
}

#[derive(Debug, Serialize)]
pub struct PhpFacts {
    memory_limit: String,
    ini: BTreeMap<String, String>,
}

#[derive(Debug, Serialize)]
pub struct SwooleFacts {
    event_workers: u32,
    task_workers: u32,
    hooks: Vec<SwooleHook>,
}

#[derive(Debug, Serialize)]
pub struct ServeFacts {
    listen: String,
}

#[derive(Debug, Serialize)]
pub struct BiaFacts {
    timeout_ms: Option<u64>,
    concurrency: Option<u32>,
    verbose: bool,
}

#[derive(Debug, Serialize)]
pub struct PathFacts {
    runtime_dir: String,
    cwd: String,
    watch: Vec<String>,
}

fn detected_parallelism() -> u32 {
    std::thread::available_parallelism().map_or(1, |cores| cores.get() as u32)
}

#[cfg(test)]
mod tests {
    use super::*;

    mod codegen {
        #![allow(dead_code)]

        include!("host_facts/codegen.rs");
    }

    use std::fs;
    use std::io::Write;
    use std::process::{Command, Stdio};

    fn config(raw: &str) -> HostConfig {
        toml::from_str(raw).unwrap()
    }

    fn gather_facts(raw: &str) -> HostFacts {
        HostFacts::gather(
            &config(raw),
            HostFactInput {
                app_env: AppEnv::Test,
                env: EnvMap::empty(),
                argv: vec!["run".to_string(), "script.php".to_string()],
                runtime_dir: Path::new("/tmp/runtime"),
                cwd: Path::new("/tmp/project"),
                memory_limit: "256M",
                verbose: true,
            },
        )
    }

    fn gather(raw: &str) -> serde_json::Value {
        serde_json::to_value(gather_facts(raw)).unwrap()
    }

    #[test]
    fn the_wire_shape_carries_every_contract_field() {
        let value = gather(
            r#"
            [php]
            ini = { "opcache.enable" = true }

            [swoole]
            event-workers = 4
            task-workers = 2
            hooks = ["tcp", "file"]

            [serve]
            listen = "0.0.0.0:8080"

            [bia]
            timeout = "30s"
            concurrency = 50

            [dev]
            watch = ["app/"]
            "#,
        );

        assert_eq!(value["contract"], CONTRACT);
        assert_eq!(value["embedded"], false);
        assert_eq!(value["argv"][1], "script.php");
        assert_eq!(value["app_env"], "test");
        assert!(value["env"]["values"].is_object());
        assert_eq!(value["php"]["memory_limit"], "256M");
        assert_eq!(value["php"]["ini"]["opcache.enable"], "1");
        assert_eq!(value["swoole"]["event_workers"], 4);
        assert_eq!(value["swoole"]["hooks"][0], "tcp");
        assert_eq!(value["serve"]["listen"], "0.0.0.0:8080");
        assert_eq!(value["bia"]["timeout_ms"], 30_000);
        assert_eq!(value["bia"]["concurrency"], 50);
        assert_eq!(value["bia"]["verbose"], true);
        assert_eq!(value["paths"]["runtime_dir"], "/tmp/runtime");
        assert_eq!(value["paths"]["watch"][0], "app/");
    }

    #[test]
    fn a_config_free_run_still_carries_the_full_shape_with_serve_null() {
        let value = gather("");

        assert_eq!(value["serve"], serde_json::Value::Null);
        assert!(value["swoole"]["event_workers"].as_u64().unwrap() >= 1);
        assert_eq!(value["bia"]["timeout_ms"], serde_json::Value::Null);
    }

    #[test]
    fn app_env_names_resolve_or_refuse_with_the_valid_set() {
        assert_eq!(AppEnv::named("prod").unwrap(), AppEnv::Prod);
        assert_eq!(AppEnv::named("").unwrap(), AppEnv::Dev);

        let error = AppEnv::named("staging").unwrap_err();

        assert!(error.contains("staging"), "got: {error}");
        assert!(
            error.contains("expected dev, test, or prod"),
            "got: {error}"
        );
    }

    #[test]
    fn generated_php_classes_round_trip_the_wire_shape() {
        let facts = gather_facts(
            r#"
            [php]
            ini = { "opcache.enable" = true }

            [swoole]
            event-workers = 4
            task-workers = 2
            hooks = ["tcp", "file"]

            [serve]
            listen = "0.0.0.0:8080"

            [bia]
            timeout = "30s"
            concurrency = 50
            "#,
        );
        let input = serde_json::to_string(&facts).unwrap();
        let output = run_php_round_trip(&input);

        assert_eq!(output.status, 0, "stderr: {}", output.stderr);
        assert_eq!(
            serde_json::from_str::<serde_json::Value>(&output.stdout).unwrap(),
            serde_json::from_str::<serde_json::Value>(&input).unwrap()
        );
    }

    #[test]
    fn generated_php_classes_refuse_contract_mismatch() {
        let mut value = serde_json::to_value(gather_facts("")).unwrap();
        value["contract"] = serde_json::Value::from(CONTRACT + 1);

        let output = run_php_round_trip(&serde_json::to_string(&value).unwrap());

        assert_eq!(output.status, 126);
        assert!(
            output
                .stderr
                .contains("handoff contract mismatch: host speaks v2, runtime expects v1"),
            "got: {}",
            output.stderr
        );
        assert!(
            output
                .stderr
                .contains("-> upgrade bia or pin phalanx-php/phalanx"),
            "got: {}",
            output.stderr
        );
    }

    struct PhpOutput {
        status: i32,
        stdout: String,
        stderr: String,
    }

    fn run_php_round_trip(input: &str) -> PhpOutput {
        let temp = tempfile::tempdir().unwrap();

        for file in codegen::generated_files() {
            let filename = Path::new(file.path).file_name().unwrap();
            fs::write(temp.path().join(filename), file.contents).unwrap();
        }

        let script = format!(
            r#"
            require {app_env:?};
            require {bia_facts:?};
            require {env_facts:?};
            require {path_facts:?};
            require {php_facts:?};
            require {serve_facts:?};
            require {swoole_facts:?};
            require {host_facts:?};

            use Phalanx\Bia\Runtime\Host\HostFacts;

            try {{
                $payload = json_decode(stream_get_contents(STDIN), true, flags: JSON_THROW_ON_ERROR);
                $facts = HostFacts::hydrate($payload);
                fwrite(STDOUT, json_encode($facts->toArray(), JSON_THROW_ON_ERROR));
            }} catch (Throwable $e) {{
                fwrite(STDERR, $e->getMessage());
                exit(126);
            }}
            "#,
            app_env = temp.path().join("AppEnv.php").display().to_string(),
            bia_facts = temp.path().join("BiaFacts.php").display().to_string(),
            env_facts = temp.path().join("EnvFacts.php").display().to_string(),
            path_facts = temp.path().join("PathFacts.php").display().to_string(),
            php_facts = temp.path().join("PhpFacts.php").display().to_string(),
            serve_facts = temp.path().join("ServeFacts.php").display().to_string(),
            swoole_facts = temp.path().join("SwooleFacts.php").display().to_string(),
            host_facts = temp.path().join("HostFacts.php").display().to_string(),
        );

        let mut child = Command::new(find_php())
            .args(["-r", &script])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .unwrap();

        child
            .stdin
            .as_mut()
            .unwrap()
            .write_all(input.as_bytes())
            .unwrap();

        let output = child.wait_with_output().unwrap();

        PhpOutput {
            status: output.status.code().unwrap_or(-1),
            stdout: String::from_utf8_lossy(&output.stdout).to_string(),
            stderr: String::from_utf8_lossy(&output.stderr).to_string(),
        }
    }

    fn find_php() -> String {
        if let Ok(path) = Command::new("which").arg("php").output() {
            let path = String::from_utf8_lossy(&path.stdout).trim().to_string();

            if !path.is_empty() {
                return path;
            }
        }

        for candidate in [
            "/opt/homebrew/opt/php@8.4/bin/php",
            "/opt/homebrew/bin/php",
            "/usr/local/bin/php",
            "/usr/bin/php",
        ] {
            if Path::new(candidate).exists() {
                return candidate.to_string();
            }
        }

        "php".to_string()
    }
}
